version: "3.5"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=http://${HOST_IP}:8096
    volumes:
      - ${APP_CONFIG_DIR}/jellyfin:/config
      - ${STORAGE_DIR}/media:/data/media
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    networks:
      - primary-tunnel
      - secondary-tunnel
    restart: unless-stopped

networks:
  primary-tunnel:
    name: primary-tunnel
  secondary-tunnel:
    name: secondary-tunnel
