---
version: "3.5"
services:
  qbittorrent:
    image: cr.hotio.dev/hotio/qbittorrent:release
    container_name: qbittorrent
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - ${APP_CONFIG_DIR}/qbittorrent:/config
      - ${STORAGE_DIR}/torrents:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - sharednetwork
    restart: unless-stopped

networks:
  sharednetwork:
    name: media_center_network
