version: '2'

services:
  db:
    image: lscr.io/linuxserver/mariadb:10.5.17-alpine
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file: .env
    volumes:
      - ${APP_CONFIG_DIR}/mariadb:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    ports:
      - 3306:3306
    networks:
      - sharednetwork

  app:
    image: nextcloud
    restart: always
    env_file: .env
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ${APP_CONFIG_DIR}/nextcloud/main:/var/www/html
      - ${APP_CONFIG_DIR}/nextcloud/apps:/var/www/html/custom_apps
      - ${APP_CONFIG_DIR}/nextcloud/config:/var/www/html/config
      - ${APP_CONFIG_DIR}/nextcloud/theme:/var/www/html/themes/icloud
      - ${DATA_DIR}:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    networks:
      - sharednetwork

networks:
  sharednetwork:
    name: nextcloud_network
