version: '3.5'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    env_file: .env
    volumes:
      - ${APP_CONFIG_DIR}/postgres:/var/lib/postgresql/data
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - sharednetwork
    restart: unless-stopped

  app:
    image: nextcloud
    container_name: nextcloud
    env_file: .env
    volumes:
      - ${APP_CONFIG_DIR}/nextcloud/main:/var/www/html
      - ${APP_CONFIG_DIR}/nextcloud/apps:/var/www/html/custom_apps
      - ${APP_CONFIG_DIR}/nextcloud/config:/var/www/html/config
      - ${APP_CONFIG_DIR}/nextcloud/theme:/var/www/html/themes/icloud
      - ${DATA_DIR}:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    ports:
      - 8080:80
    networks:
      - sharednetwork
    restart: always

networks:
  sharednetwork:
    name: nextcloud_network
