---
version: "3.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 2M
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${DOCKER_CONFIG_DIR}/docker/readarr-config:/config
      - ${DATA_DIR}/data:/data
    ports:
      - 8787:8787
    restart: unless-stopped