---
version: "3.5"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 6M
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/radarr:/config
      - ${STORAGE_DIR}:/data
    ports:
      - 7878:7878
    networks:
      - sharednetwork
    restart: unless-stopped

networks:
  sharednetwork:
    name: media_center_network