name: beszel

include:
  - beszelagent-compose.yaml
  
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8090:8090
    volumes:
      - ${APP_CONFIG_DIR}/beszel:/beszel_data
