name: beszel

services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    network_mode: host
    environment:
      PORT: 45876
      KEY: "${BESZEL_KEY}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/hotflix/shows:/extra-filesystems/sdc1:ro
      - /srv/hotflix/movies:/extra-filesystems/sdd2:ro
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"
    restart: unless-stopped
