name: beszel
  
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    network_mode: host
    volumes:
      - ${APP_CONFIG_DIR}/beszel:/beszel_data
    ports:
      - 8090:8090
    restart: unless-stopped

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    network_mode: host
    environment:
      PORT: 45876
      KEY: "${BESZEL_KEY}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
