name: beszel
  
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    volumes:
      - ${APP_CONFIG_DIR}/beszel:/beszel_data
    ports:
      - 8090:8090
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"
    networks:
      - tailproxy
    restart: unless-stopped

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    network_mode: host
    environment:
      PORT: 45876
      KEY: "${BESZEL_KEY}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"
    restart: unless-stopped

networks:
  tailproxy:
    name: tailproxy
    external: true
