name: caddy

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    volumes:
      - ./../configs/Caddyfile:/etc/caddy/Caddyfile
      - ${APP_CONFIG_DIR}/caddy/srv:/srv
      - ${APP_CONFIG_DIR}/caddy/data:/data
      - ${APP_CONFIG_DIR}/caddy/config:/config
    ports:
      - 80:80
      - 443:443
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    restart: unless-stopped
