name: changed

services:
  changed-app:
    container_name: changed-app
    image: dgtlmoon/changedetection.io:latest
    depends_on:
      changed-browser:
        condition: service_started
    volumes:
      - ${APP_CONFIG_DIR}/changed:/datastore
      - ./../configs/changed_headers.txt:/datastore/headers.txt
    environment:
      - TZ=${TIMEZONE}
      - FETCH_WORKERS=2
      - HIDE_REFERER=true
      - DISABLE_VERSION_CHECK=true
      - MINIMUM_SECONDS_RECHECK_TIME=5
      - PLAYWRIGHT_DRIVER_URL=ws://changed-browser:3000?stealth=1&--disable-web-security=true
    ports:
      - 5000:5000
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "changed"
      tsdproxy.ephemeral: "false"
    networks:
      - tailproxy
    restart: unless-stopped

  changed-browser:
    container_name: changed-browser
    image: dgtlmoon/sockpuppetbrowser:latest
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=600000
      - DEFAULT_BLOCK_ADS=false
      - DEFAULT_STEALTH=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
    networks:
      - tailproxy
    restart: unless-stopped

networks:
  tailproxy:
    name: tailproxy
    external: true
