name: mealie

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    volumes:
      - ${APP_CONFIG_DIR}/mealie:/app/data
    environment:
      - ALLOW_SIGNUP=true
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "cook"
      tsdproxy.ephemeral: "false"
    networks:
      - tailproxy
    restart: unless-stopped

networks:
  tailproxy:
    name: tailproxy
    external: true
