name: mealie

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    volumes:
      - ${APP_CONFIG_DIR}/mealie:/app/data
    environment:
      - TZ=${TIMEZONE}
      - ALLOW_SIGNUP=true
      - BASE_URL=http://cook.home.lab
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "cook"
      tsdproxy.ephemeral: "false"
    ports:
      - 9001:9000
    networks:
      - tailproxy
    restart: unless-stopped

networks:
  tailproxy:
    name: tailproxy
    external: true
