name: pairdrop

services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    environment:
      - TZ=${TIMEZONE}
      - RATE_LIMIT=true
      - WS_FALLBACK=true
    ports:
      - 3000:3000
    tmpfs:
      - /run:exec
    read_only: true
    restart: unless-stopped
