name: pihole

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      - TZ=${TIMEZONE}
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    volumes:
      - '${APP_CONFIG_DIR}/pihole/etc/pihole:/etc/pihole'
      - '${APP_CONFIG_DIR}/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    restart: unless-stopped
