name: portainer

services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 256M
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_CONFIG_DIR}/portainer:/data
    ports:
      - 8000:8000
      - 9443:9443
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "portainer"
      tsdproxy.ephemeral: "false"
    networks:
      - tailscale
    restart: always

networks:
  tailscale:
    name: tailscale
    external: true