name: tailscale

services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1.4.3
    container_name: tailproxy
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../configs:/config
      - ${APP_CONFIG_DIR}/tsdproxy:/data
    networks:
      - tailproxy
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    restart: unless-stopped

networks:
  tailproxy:
    name: tailproxy
