version: '3.5'

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    env_file: .env
    deploy:
      replicas: ${REPLICAS}
      resources:
        limits:
          cpus: "0.75"
          memory: 300M
        reservations:
          cpus: "0.10"
          memory: 100M
    environment:
      - PUID=${UID}
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${APP_CONFIG_DIR}/plex:/config
      - ${STORAGE_DIR}/media:/data/media
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    networks:
      - network

networks:
  network:
    name: plex_network