version: "3.5"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${APP_CONFIG_DIR}/plex:/config
      - ${MEDIA_ONE_DIR}/media:/data/media
    restart: unless-stopped
