version: "3.5"
services:
  primary:
    image: cloudflare/cloudflared:latest
    container_name: tunnel_primary
    command: tunnel run ${PRIMARY_TUNNEL_NAME}
    volumes:
      - ${APP_CONFIG_DIR}/tunnel/primary:/home/nonroot/.cloudflared/
    networks:
      - primary
      - secondary
    restart: unless-stopped

  secondary:
    image: cloudflare/cloudflared:latest
    container_name: tunnel_secondary
    command: tunnel run ${SECONDARY_TUNNEL_NAME}
    volumes:
      - ${APP_CONFIG_DIR}/tunnel/secondary:/home/nonroot/.cloudflared/
    networks:
      - primary
      - secondary
    restart: unless-stopped

networks:
  primary:
    name: primary-tunnel
  secondary:
    name: secondary-tunnel
