version: "3.5"
services:
  portainer:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    volumes:
      - ${APP_CONFIG_DIR}/cloudflared:/home/nonroot/.cloudflared/
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    name: tunnel