version: "3.5"
services:
  prime:
    image: cloudflare/cloudflared:latest-arm64
    container_name: tunnel_prime
    command: tunnel --no-autoupdate run --token ${TUNNEL_PRIME_TOKEN}
    networks:
      - prime
    restart: unless-stopped

networks:
  prime:
    name: tunnel-prime
