---
version: "3.5"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/sonarr:/config
      - ${MEDIA_TWO_DIR}:/data
    ports:
      - 8989:8989
    networks:
      - sharednetwork
    restart: unless-stopped

networks:
  sharednetwork:
    name: media_center_network