---
version: "3.5"
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${GHOSTFOLIO_DB}?sslmode=prefer
      NODE_ENV: production
      REDIS_HOST: 'redis'
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 3333:3333
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    restart: unless-stopped
