---
version: "3.5"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/lidarr:/config
      - ${STORAGE_DIR}:/data
    ports:
      - 8686:8686
    networks:
      - sharednetwork
    restart: unless-stopped

networks:
  sharednetwork:
    name: media_center_network