version: '3.5'

services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    env_file: .env
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 250M
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/docker/jellyfin-config:/config
      - ${STORAGE_DIR}/data/media:/data/media
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    networks:
      - network

networks:
  network:
    name: jellyfin_network