---
version: "3.5"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 400M
        reservations:
          cpus: "0.10"
          memory: 100M
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${DOCKER_CONFIG_DIR}/docker/plex-config:/config
      - ${DATA_DIR}/data/media:/data/media
    restart: unless-stopped