---
version: "3.5"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    env_file: ./../../.env
    container_name: sonarr
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 6M
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/sonarr:/config
      - ${STORAGE_DIR}:/data
    ports:
      - 8989:8989
    networks:
      - sharednetwork
    restart: unless-stopped

networks:
  sharednetwork:
    name: media_center_network