version: '2'
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changed_app
    volumes:
      - ${APP_CONFIG_DIR}/changed:/datastore
    environment:
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - PLAYWRIGHT_DRIVER_URL=ws://changed_browser:3000/
    ports:
      - 5000:5000
    restart: unless-stopped

  chrome:
    image: browserless/chrome:1.59-chrome-stable
    container_name: changed_browser
    restart: unless-stopped

  apprise:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: changed_apprise
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/apprise:/config
    ports:
      - 8000:8000
    restart: unless-stopped
