version: "3.5"
services:
  changed:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changed
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
    volumes:
      - /var/data/tmp/config/changed:/config
    ports:
      - 5000:5000
    restart: unless-stopped

  browser-chrome:
      hostname: browser-chrome
      image: selenium/standalone-chrome-debug:3.141.59
      environment:
          - VNC_NO_PASSWORD=1
          - SCREEN_WIDTH=1920
          - SCREEN_HEIGHT=1080
          - SCREEN_DEPTH=24
      volumes:
          # Workaround to avoid the browser crashing inside a docker container
          # See https://github.com/SeleniumHQ/docker-selenium#quick-start
          - /dev/shm:/dev/shm
      restart: unless-stopped
