name: changed

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    depends_on:
      sockpuppetbrowser:
        condition: service_started
    volumes:
      - ${APP_CONFIG_DIR}/changed:/datastore
    environment:
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
      - HIDE_REFERER=true
      - FETCH_WORKERS=3
    ports:
      - 5000:5000
    restart: unless-stopped

  sockpuppetbrowser:
    container_name: sockpuppetbrowser
    image: dgtlmoon/sockpuppetbrowser:latest
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    restart: unless-stopped

  browser-chrome:
    container_name: browser-chrome
    image: seleniarm/standalone-chromium:4.0.0-20211213
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped

  apprise:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: changed_apprise
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/apprise:/config
    ports:
      - 8000:8000
    restart: unless-stopped
