name: changed

services:
  changedetection:
    container_name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io
    depends_on:
      sockpuppetbrowser:
        condition: service_started
    volumes:
      - ${APP_CONFIG_DIR}/changed:/datastore
    environment:
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - PLAYWRIGHT_DRIVER_URL=ws://sockpuppetbrowser:3000
      - HIDE_REFERER=true
      - FETCH_WORKERS=2
    ports:
      - 5000:5000
    restart: unless-stopped

  puppetbrowser:
    container_name: sockpuppetbrowser
    image: dgtlmoon/sockpuppetbrowser:latest
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    restart: unless-stopped

  apprise:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: changed_apprise
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/apprise:/config
    ports:
      - 8000:8000
    restart: unless-stopped
