version: '2'
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - ${APP_CONFIG_DIR}/changed:/datastore
    environment:
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/
    ports:
      - 5000:5000
    networks:
      - primary-tunnel
      - secondary-tunnel
    restart: unless-stopped

  playwright-chrome:
    hostname: playwright-chrome
    image: browserless/chrome
    networks:
      - primary-tunnel
      - secondary-tunnel
    restart: unless-stopped

networks:
  primary-tunnel:
    name: primary-tunnel
  secondary-tunnel:
    name: secondary-tunnel
