---
version: "3.5"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    env_file: ./../../.env
    container_name: readarr
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 6M
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/readarr:/config
      - ${STORAGE_DIR}:/data
    ports:
      - 8787:8787
    networks:
      - sharednetwork
    restart: unless-stopped

networks:
  sharednetwork:
    name: media_center_network