---
version: "3.5"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    deploy:
      resources:
        limits:
          cpus: "2.5"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 300M
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${DOCKER_CONFIG_DIR}/docker/jellyfin-config:/config
      - ${DATA_DIR}/data/media:/data/media
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    networks:
      - sharednetwork
    restart: unless-stopped

networks:
  sharednetwork:
    name: media_center_network